name: "Setup Docker Buildx"
description: "Setup QEMU and Docker Buildx"
author: 'soramitsukhmer-lab'
branding:
  icon: 'anchor'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
